"""Postgresql migration

Revision ID: 1ab29134143b
Revises: 65f9cc74d57e
Create Date: 2024-07-21 23:33:57.367841

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1ab29134143b'
down_revision = '65f9cc74d57e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('races',
               existing_type=postgresql.BYTEA(),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('levels',
               existing_type=postgresql.BYTEA(),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('levels',
               existing_type=sa.String(length=50),
               type_=postgresql.BYTEA(),
               existing_nullable=False)
        batch_op.alter_column('races',
               existing_type=sa.String(length=50),
               type_=postgresql.BYTEA(),
               existing_nullable=False)

    # ### end Alembic commands ###
