"""Changed models

Revision ID: ca38274b9819
Revises: 160ad17ae96d
Create Date: 2024-06-25 10:23:33.151953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca38274b9819'
down_revision = '160ad17ae96d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('levels',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.PickleType(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('levels',
               existing_type=sa.PickleType(),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)

    # ### end Alembic commands ###
