"""Changed models

Revision ID: f42eaf1cb993
Revises: ca38274b9819
Create Date: 2024-06-25 10:48:57.531990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f42eaf1cb993'
down_revision = 'ca38274b9819'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('races', sa.String(length=10), nullable=False))
        batch_op.drop_column('race')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('race', sa.VARCHAR(length=10), nullable=False))
        batch_op.drop_column('races')

    # ### end Alembic commands ###
